variables:
  ARM_PASS: $(adminPass)

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '101-webapp-linux-managed-mysql'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'HCARROLL-TEST Service Connection'
    subscriptionId: '90b70eaf-cc01-414a-ac78-acc96a6aec0d'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'HCARROLL-TEST'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.json'
    csmParametersFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.parameters.json'
    overrideParameters: '-siteName "$(siteName)" -administratorLogin "$(adminUser)" -administratorLoginPassword "$(ARM_PASS)"'
    deploymentMode: 'Incremental'